import { getSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Playwright Auth POC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: `/admin`,
        permanent: false,
      },
    };
  } else {
    return {
      redirect: {
        destination: `/signin`,
        permanent: false,
      },
    };
  }
}
